### ISSUE TITLE
Stop Button Transport Control on Maschine

### ISSUE THREAD

**Issue by reflekshun** [teotigraphix/Maschine4Bitwig#52]
If possible, implement stop button control.

Currently, pressing play during playback does stop, but moves blue restart locator in Bitwig to current playhead position)

**Comment by teotigraphix** [comment]
Press restart once and it does the same thing the Stop button does.

But when you press play, it starts from the play arrow just like Bitwig, is this what you want?

If not, you need to tell me how it's done in Bitwig because I am having a brain fart on how to continue play from the playhead.

**Comment by reflekshun** [comment]
Thanks for the response! 

Pressing restart once doesn't stop playback over here, it restarts playback from the blue arrow immediately, continuing to playback the track. This is a very useful button but it doesn't stop playback. 

When you press play on Maschine it will play on from playhead, which is good.

When you press play on Maschine during playback, it acts as clicking the play button in Bitwig transport with the mouse. It stops playback, but the blue arrow moves up to the current position, next time you press play will be from the same spot as you stopped. 

I believe that kind of behavior is buried in clicking play on the transport bar in Bitwig (something most people don't do) as it is less commonly used. Most people are hitting the spacebar and used to this playback behavior - pressing spacebar during playback stops playback, and the blue arrow remains in the same spot. So a further spacebar press will start playback from the same position every time, rather than a moving target.

**Comment by teotidev** [comment]
Ok I get it.

I am mainly in clip launcher view making loops these days but the spacebar is what I was looking for because the Maschine does emulate the play button, that is the API play/stop behavior.

I need to look at the docs and see if there is something else I can use other than play() to do what you want.

As for the Restart button, that is weird, I tested it on the Studio and it stopped the transport and I hit it again and it restarts from 0. I think i may have messed something up witht he 2 different impls.

I'll let you know.

I'm curious, I am not really actively working on this at the moment because it didn't seem like there was much interest but, if you want to actively use the MK2 with Bitwig, you could help me get 1.2 implemented and I could start doing some dev on the scripts again. Let me know.

**Comment by reflekshun** [comment]
Absolutely interested in helping you getting it implemented for 1.2!

**Comment by teotigraphix** [comment]
Ok well you got me working on it again as you can see. Just watch the changes wiki page and commits.

I will be digging deep, right now I have my studio hooked up, will need to kype the MK2 from my sons room, haha.
